### ISSUE TITLE
Automatic Docker Builds

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [RocketDerp/lemmy_helper#2]
See- my working example over here: https://github.com/XtremeOwnageDotCom/FediseerDocker/blob/master/.github/workflows/docker-image.yml

Essentially, github has a built in container registry. You can automatically build images, and push to this container registry, when pushing to a specific branch (if specified)

The benefit of this, anyone using this container, can much more easily pull it in.

Also- if you can get GHCR setup and working for this, I will gladly spin up a few kubernetes manifests for you too, to give another method of deployment for the few of us running lemmy on k8s.

**Comment by RocketDerp** [comment]
I appreciate the participation. I have not worked with GHCR and such before, so I'm not jumping on it. Feel free to guide this more. I'm not sure if anyone else has even noticed this project.

Don't be afraid to clutter up issues with conversation at this point in the project. Feedback and alternate approaches are welcome.

**Comment by XtremeOwnageDotCom** [comment]
@RocketDerp its pretty much literally as easy as copying the workflow file I linked, and dropping into this repo.

Actually- that file is the first time I have worked with GHCR as of... a week ago. And, I was surprised at how easy the entire process was.
